// <auto-generated />
namespace Proiect_IAME.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Add_DurateServicii : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_DurateServicii));
        
        string IMigrationMetadata.Id
        {
            get { return "202005071924546_Add_DurateServicii"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
