// <auto-generated />
namespace Proiect_IAME.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Add_NumeContact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_NumeContact));
        
        string IMigrationMetadata.Id
        {
            get { return "202006022022007_Add_NumeContact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
